services:
  - type: web
    plan: free
    name: Zaid
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 -m Zaid
    repo: https://github.com/ITZ-ZAID/ZAID-USERBOT      
    branch: master
    envVars:
      - key:  API_ID 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: API_HASH 
        sync: false
      - key: CACHE_TIME
        sync: false
      - key: USE_CAPTION_FILTER
        sync: false
      - key:  UPSTREAM_REPO
        sync: false
      - key:  TIMEZONE
        sync: false
      - key:  PORT
        sync: false
      - key:  NEWGRP
        sync: false
      - key:  SPELL_IMG
        sync: false
      - key:  NOR_IMG
        sync: false
      - key:  PICS 
        sync: false
      - key:  FILDLT_CNL
        sync: false
      - key:  AUTH_GROUPS
        sync: false
      - key:  AUTH_CHANNEL
        sync: false
      - key:  AUTH_USERS
        sync: false
      - key:  CHANNELS
        sync: false
      - key:  ADMINS
        sync: false
      - key: DATABASE_URI 
        sync: false
      - key: DATABASE_NAME 
        sync: false
      - key: COLLECTION_NAME  
        sync: false
      - key: CHNL_LNK 
        sync: false
      - key: SUPPORT_CHAT  
        sync: false
      - key: MSG_ALRT  
        sync: false
      - key: CHNL_LNK  
        sync: false
      - key: FILE_CHANNEL_LINK  
        sync: false
      - key: FILE_CHANNEL   
        sync: false
      - key: SUPPORT_GROUP  
        sync: false
      - key: LOG_CHANNEL  
        sync: false
      - key: RQST_LOG_CHANNEL  
        sync: false
      - key: SINGLE_BUTTON   
        sync: false
      - key: IMDB  
        sync: false
      - key: P_TTI_SHOW_OFF  
        sync: false
      - key: CUSTOM_FILE_CAPTION  
        sync: false
      - key: IMDB_TEMPLATE  
        sync: false
      - key: LONG_IMDB_DESCRIPTION  
        sync: false
      - key: SPELL_CHECK_REPLY   
        sync: false
      - key: MAX_LIST_ELM  
        sync: false
      - key: INDEX_REQ_CHANNEL  
        sync: false
      - key: FILE_STORE_CHANNEL  
        sync: false
      - key: MELCOW_NEW_USERS   
        sync: false
      - key: PROTECT_CONTENT  
        sync: false
      - key: PUBLIC_FILE_STORE  
        sync: false
      - key: AUTO_FFILTER  
        sync: false
      - key: AUTO_DELETE   
        sync: false
      - key: MAUTO_DELETE  
        sync: false
      - key: SPL_DELETE_TIME
        sync: false
      - key: DELETE_TIME  
        sync: false
     sync: false        
    autoDeploy: false
